server:
  port: 0
  
spring:
  application:
    name: CITIZEN-SERVICE  datasource:    url: jdbc:mariadb://localhost:3306/CitizenDB
    username: root
    password: root
    driver-class-name : org.mariadb.jdbc.Driver 
  jpa:
   hibernate:
    ddl-auto: update
   show-sql: true
   database-platfrom: org.hibernate.dialect.MariaDBDialect     
   
   