server:
  port: 0
  
spring:
  application:
    name: VACCINATION-CENTRE-SERVICE  datasource:    url: jdbc:mariadb://localhost:3306/VaccinationCentreDB
    username: root
    password: root
    driver-class-name : org.mariadb.jdbc.Driver 
  jpa:
   hibernate:
    ddl-auto: update
   show-sql: true
   database-platfrom: org.hibernate.dialect.MariaDBDialect     
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
resilience4j.circuitbreaker:  
   instances:
     circuit-breaker-for-citizen:
            minimumNumberOfCalls: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 5s 
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowSize: 10
            slidingWindowType: COUNT_BASED
            automaticTransitionFromOpenToHalfOpenEnabled: true